# Generated by Django 3.2.7 on 2021-09-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('option_1', models.CharField(max_length=200)),
                ('option_2', models.CharField(max_length=200)),
                ('option_3', models.CharField(max_length=200)),
                ('option_4', models.CharField(max_length=200)),
                ('option_1_count', models.IntegerField()),
                ('option_2_count', models.IntegerField()),
                ('option_3_count', models.IntegerField()),
                ('option_4_count', models.IntegerField()),
            ],
        ),
    ]
